# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
df = pd.read_csv("Churn_Modelling.csv")

In [18]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [19]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [20]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [21]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

One Hot Encoding the "Geography" column

In [25]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [28]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.2)

### Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [31]:
from tensorflow.keras.models import Sequential

model = Sequential()

### Adding the input layer and the first hidden layer

In [32]:
from tensorflow.keras.layers import Dense
model.add(Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [33]:
model.add(Dense(units=6, activation='relu'))

### Adding the output layer

In [34]:
model.add(Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [35]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [36]:
model.fit(X_train, y_train, batch_size=32, epochs=50)

Epoch 1/50
250/250 [==============================] - 1s 2ms/step - loss: 0.5719 - accuracy: 0.7654
Epoch 2/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4749 - accuracy: 0.8000
Epoch 3/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4441 - accuracy: 0.8058
Epoch 4/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4282 - accuracy: 0.8144
Epoch 5/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4160 - accuracy: 0.8201
Epoch 6/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4033 - accuracy: 0.8291
Epoch 7/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3874 - accuracy: 0.8366
Epoch 8/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3728 - accuracy: 0.8475
Epoch 9/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3624 - accuracy: 0.8540
Epoch 10/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3553 - accuracy: 0.8575

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [40]:
x = np.array([[600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]])
x[:, 2] = le.transform(x[:, 2])
x = ct.transform(x)
x = sc.transform(x)
predict = model.predict(x) > 0.5

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [44]:
predicts = model.predict(X_test) > 0.5

### Making the Confusion Matrix

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, predicts))
print(accuracy_score(y_test, predicts))


[[1492   71]
 [ 226  211]]
0.8515
